
/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <Entity/CarSetupsPackageEntity.h>

#include <Exceptions/ValidationException.h>


namespace DogGE{
    namespace F1_2022{
        CarSetupsPackageEntity::CarSetupsPackageEntity(){}
CarSetupsPackageEntity::CarSetupsPackageEntity(char* rawData,int size,int offset){
this->setHeader(HeaderEntity(rawData,size,offset+0));
for(int i=0;i<22;i++){this->setCarSetups(i,CarSetupDataEntity(rawData,size,offset+24+i*49));}
}

        HeaderEntity CarSetupsPackageEntity::getHeader(){return this->header;}
CarSetupDataEntity* CarSetupsPackageEntity::getCarSetups(){return this->carSetups;}

        void CarSetupsPackageEntity::setHeader(HeaderEntity header){this->header = header;}
void CarSetupsPackageEntity::setCarSetups(int i,CarSetupDataEntity carSetups){this->carSetups[i] = carSetups;}


        std::string CarSetupsPackageEntity::getTableName(){
            return "CarSetupsPackageEntity";
        }
        std::string CarSetupsPackageEntity::getTableDefinition(){
            return "CREATE TABLE IF NOT EXISTS CarSetupsPackageEntity("
            "`id` INTEGER PRIMARY KEY AUTOINCREMENT,`header` REAL,`carSetups` INTEGER)";
        }
        
        void CarSetupsPackageEntity::matchIntData(std::string column,int data){
            DogGE::Database::AbstractEntity::matchIntData(column,data);

        }
        void CarSetupsPackageEntity::matchInt64Data(std::string column,int64_t data){
            
        }
        void CarSetupsPackageEntity::matchRealData(std::string column,float data){
            
        }
        void CarSetupsPackageEntity::matchStringData(std::string column,std::string data){}
        void CarSetupsPackageEntity::matchRawData(std::string column,char* data,int length){
            
        }

        std::map<std::string,int> CarSetupsPackageEntity::getIntMap(){
            std::map<std::string,int> ret = DogGE::Database::AbstractEntity::getIntMap();
            
            return ret;
        }
        std::map<std::string,int64_t> CarSetupsPackageEntity::getInt64Map(){
            std::map<std::string,int64_t> ret;
            
            return ret;
        }
        std::map<std::string,float> CarSetupsPackageEntity::getRealMap(){
            std::map<std::string,float> ret;
            
            return ret;
        }
        std::map<std::string,std::string> CarSetupsPackageEntity::getStringMap(){
            std::map<std::string,std::string> ret;
            return ret;
        }
        std::map<std::string,std::pair<char*,int>> CarSetupsPackageEntity::getRawMap(){
            std::map<std::string,std::pair<char*,int>> ret;
            
            return ret;
        }
    }
}                                                                        