/**
 * @file ExceptionTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <Exceptions/ValidationException.h>

namespace DogGE{
    namespace F1_2022{
        ValidationException::ValidationException(){
            this->message = "Validation Fehler";
        }
        
        const char* ValidationException::what() const throw(){
            return this->message.c_str();;
        }
    }
}                         