
/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <F1DataEntity_2022.h>

#include <Exceptions/ValidationException.h>


namespace DogGE{
    namespace F1_2022{
        F1DataEntity::F1DataEntity(){}
F1DataEntity::F1DataEntity(char* rawData,int size){
this->setPacketFormat(*((uint16_t*)(rawData+0)));
if(this->getPacketFormat() != 2022){throw ValidationException();}
this->setGameMajorVersion(*((uint8_t*)(rawData+2)));
this->setGameMinorVersion(*((uint8_t*)(rawData+3)));
this->setPacketVersion(*((uint8_t*)(rawData+4)));
this->setPacketId(*((uint8_t*)(rawData+5)));
this->setSessionUID(*((uint64_t*)(rawData+6)));
this->setSessionTime(*((float*)(rawData+14)));
this->setFrameIdentifier(*((uint32_t*)(rawData+18)));
this->setPlayerCarIndex(*((uint8_t*)(rawData+22)));
this->setSecondaryPlayerCarIndex(*((uint8_t*)(rawData+23)));
this->packetData = rawData;
this->packetSize = size;
}

        uint16_t F1DataEntity::getPacketFormat(){return this->packetFormat;}
uint8_t F1DataEntity::getGameMajorVersion(){return this->gameMajorVersion;}
uint8_t F1DataEntity::getGameMinorVersion(){return this->gameMinorVersion;}
uint8_t F1DataEntity::getPacketVersion(){return this->packetVersion;}
uint8_t F1DataEntity::getPacketId(){return this->packetId;}
uint64_t F1DataEntity::getSessionUID(){return this->sessionUID;}
float F1DataEntity::getSessionTime(){return this->sessionTime;}
uint32_t F1DataEntity::getFrameIdentifier(){return this->frameIdentifier;}
uint8_t F1DataEntity::getPlayerCarIndex(){return this->playerCarIndex;}
uint8_t F1DataEntity::getSecondaryPlayerCarIndex(){return this->secondaryPlayerCarIndex;}
char* F1DataEntity::getPacketData(){return this->packetData;}
int F1DataEntity::getPacketSize(){return this->packetSize;}

        void F1DataEntity::setPacketFormat(uint16_t packetFormat){this->packetFormat = packetFormat;}
void F1DataEntity::setGameMajorVersion(uint8_t gameMajorVersion){this->gameMajorVersion = gameMajorVersion;}
void F1DataEntity::setGameMinorVersion(uint8_t gameMinorVersion){this->gameMinorVersion = gameMinorVersion;}
void F1DataEntity::setPacketVersion(uint8_t packetVersion){this->packetVersion = packetVersion;}
void F1DataEntity::setPacketId(uint8_t packetId){this->packetId = packetId;}
void F1DataEntity::setSessionUID(uint64_t sessionUID){this->sessionUID = sessionUID;}
void F1DataEntity::setSessionTime(float sessionTime){this->sessionTime = sessionTime;}
void F1DataEntity::setFrameIdentifier(uint32_t frameIdentifier){this->frameIdentifier = frameIdentifier;}
void F1DataEntity::setPlayerCarIndex(uint8_t playerCarIndex){this->playerCarIndex = playerCarIndex;}
void F1DataEntity::setSecondaryPlayerCarIndex(uint8_t secondaryPlayerCarIndex){this->secondaryPlayerCarIndex = secondaryPlayerCarIndex;}
void F1DataEntity::setPacketData(char* packet,int size){for(int i=0;i<size;i++){this->packetData[i] = packet[i];}this->packetSize = size;}


        std::string F1DataEntity::getTableName(){
            return "F1DataEntity";
        }
        std::string F1DataEntity::getTableDefinition(){
            return "CREATE TABLE IF NOT EXISTS F1DataEntity("
            "`id` INTEGER PRIMARY KEY AUTOINCREMENT,`packetFormat` INTEGER,`gameMajorVersion` INTEGER,`gameMinorVersion` INTEGER,`packetVersion` INTEGER,`packetId` INTEGER,`sessionUID` BIGINT,`sessionTime` REAL,`frameIdentifier` INTEGER,`playerCarIndex` INTEGER,`secondaryPlayerCarIndex` INTEGER,`packet` BLOB)";
        }
        
        void F1DataEntity::matchIntData(std::string column,int data){
            DogGE::Database::AbstractEntity::matchIntData(column,data);

        }
        void F1DataEntity::matchInt64Data(std::string column,int64_t data){
            
        }
        void F1DataEntity::matchRealData(std::string column,float data){
            if(column.compare("sessionTime") == 0){
this->setSessionTime(data);
}
        }
        void F1DataEntity::matchStringData(std::string column,std::string data){}
        void F1DataEntity::matchRawData(std::string column,char* data,int length){
            if(column.compare("packet") == 0){this->setPacketData(data,length);}
        }

        std::map<std::string,int> F1DataEntity::getIntMap(){
            std::map<std::string,int> ret = DogGE::Database::AbstractEntity::getIntMap();
            
            return ret;
        }
        std::map<std::string,int64_t> F1DataEntity::getInt64Map(){
            std::map<std::string,int64_t> ret;
            
            return ret;
        }
        std::map<std::string,float> F1DataEntity::getRealMap(){
            std::map<std::string,float> ret;
            ret.insert(std::pair<std::string,float>("sessionTime",this->getSessionTime()));
            return ret;
        }
        std::map<std::string,std::string> F1DataEntity::getStringMap(){
            std::map<std::string,std::string> ret;
            return ret;
        }
        std::map<std::string,std::pair<char*,int>> F1DataEntity::getRawMap(){
            std::map<std::string,std::pair<char*,int>> ret;
            ret.insert( std::pair<std::string,std::pair<char*,int>>("packet",std::pair<char*,int>( this->getPacketData(),this->getPacketSize() )) );
            return ret;
        }
    }
}                                                                        