/**
 * @file RecorderTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */
 

#include <Recorder_2022.h>
#include <DatabaseBuilder.h>
#include <UdpClient.h>
#include <F1DataEntity_2022.h>
#include <Exceptions/NothingRecivedException.h>
#include <RecordState.h>
#include <array>

namespace DogGE{
    namespace F1_2022{

        Recorder_2022::Recorder_2022(){

        }

        void Recorder_2022::setOutput(std::string output){
            this->mOutput = output;
        }

        void Recorder_2022::init(){
            mRecivedPackages = 0;
            mParsedPackages = 0;
            CTelemetry::Recorder::ProducerConsumerRecorder::init();
        }
        void Recorder_2022::producer(){
            DogGE::Network::UdpClient client;
            client.init("127.0.0.1","9996");
            do{
                try{
                    std::array<char,2000> buf = client.recvData<2000>();
                    mtx.lock();
                    this->mQueue.push(buf);
                    mtx.unlock();
                    mRecivedPackages++;
                } catch(DogGE::Network::NothingRecivedException &e){
                }
                
            } while(this->bRun);
        }
        void Recorder_2022::consumer(){
            this->mDatabase = DogGE::Database::DatabaseBuilder::fromMemory();
            F1DataEntity dummyEntity = F1DataEntity();
            DogGE::Database::PrepareStatement* createStatement = this->mDatabase->prepareStatement(dummyEntity.getTableDefinition());
            createStatement->execute();
            delete createStatement;
            DogGE::Database::PrepareStatement* insertStatement = this->mDatabase->prepareStatement("INSERT INTO F1DataEntity(`packetFormat`,`gameMajorVersion`,`gameMinorVersion`,`packetVersion`,`packetId`,`sessionUID`,`sessionTime`,`frameIdentifier`,`playerCarIndex`,`secondaryPlayerCarIndex`,`packet`) VALUES (@packetFormat0,@gameMajorVersion0,@gameMinorVersion0,@packetVersion0,@packetId0,@sessionUID0,@sessionTime0,@frameIdentifier0,@playerCarIndex0,@secondaryPlayerCarIndex0,@packet0),(@packetFormat1,@gameMajorVersion1,@gameMinorVersion1,@packetVersion1,@packetId1,@sessionUID1,@sessionTime1,@frameIdentifier1,@playerCarIndex1,@secondaryPlayerCarIndex1,@packet1)");
            int packageNum = 2;
            do{
                mtx.lock();
                if(mQueue.size() < packageNum){
                    mtx.unlock();
                    continue;
                }
                mtx.unlock();

                for(int i=0; i < packageNum;i++){
                    mtx.lock();
                    std::array<char,2000> datagram = mQueue.front();
                    mQueue.pop();
                    mtx.unlock();
                    F1DataEntity entity = F1DataEntity(datagram.data(),datagram.size());
                    insertStatement->setIntParam(i*11+1,entity.getPacketFormat());
insertStatement->setIntParam(i*11+2,entity.getGameMajorVersion());
insertStatement->setIntParam(i*11+3,entity.getGameMinorVersion());
insertStatement->setIntParam(i*11+4,entity.getPacketVersion());
insertStatement->setIntParam(i*11+5,entity.getPacketId());
insertStatement->setInt64Param(i*11+6,entity.getSessionUID());
insertStatement->setFloatParam(i*11+7,entity.getSessionTime());
insertStatement->setIntParam(i*11+8,entity.getFrameIdentifier());
insertStatement->setIntParam(i*11+9,entity.getPlayerCarIndex());
insertStatement->setIntParam(i*11+10,entity.getSecondaryPlayerCarIndex());
insertStatement->setBlobParam(i*11+11,entity.getPacketData(),entity.getPacketSize());

                }
                insertStatement->execute();
                insertStatement->resetParam();
                //this->mDatabase->persistData(&entity);
                mParsedPackages+=packageNum;
                
            } while(this->bRun);
            delete insertStatement;
            DogGE::Database::DatabaseBuilder::convertMemoryIntoFile(this->mDatabase,this->mOutput);
            delete this->mDatabase;
            this->mDatabase = nullptr;
        }
        CTelemetry::Recorder::RecordState Recorder_2022::getState(){
            
            if(this->mDatabase != nullptr){
                //DogGE::Database::DatabaseBuilder::convertMemoryIntoFile(this->mDatabase,this->mOutput);
            }
            
            int recivedPackages = this->mRecivedPackages;
            int parsedPackages = this->mParsedPackages;
            int queueSize = mQueue.size();
            this->mRecivedPackages = 0;
            this->mParsedPackages = 0;
            return CTelemetry::Recorder::RecordState(recivedPackages,parsedPackages,0,queueSize);
        }
    }
}                                                                                                      