

#[derive(Clone)]
pub struct SPageFilePhysics{
    pub packet_id:i32,
    pub gas:f32,
    pub brake:f32,
    pub fuel:f32,
    pub gear:i32,
    pub rpms:i32,
    pub steer_angle:f32,
    pub speed_kmh:f32,
    pub velocity:[f32;3],
    pub acc_g:[f32;3],
    pub wheel_slip:[f32;4],
    pub wheel_load:[f32;4],
    pub wheels_pressure:[f32;4],
    pub wheel_angular_speed:[f32;4],
    pub tyre_wear:[f32;4],
    pub tyre_dirty_level:[f32;4],
    pub tyre_core_temperature:[f32;4],
    pub camber_rad:[f32;4],
    pub suspension_travel:[f32;4],
    pub drs:f32,
    pub tc:f32,
    pub heading:f32,
    pub pitch:f32,
    pub roll:f32,
    pub cg_height:f32,
    pub car_damage:[f32;5],
    pub number_of_tyres_out:i32,
    pub pit_limiter_on:i32,
    pub abs:f32,
    pub kers_charge:f32,
    pub kers_input:f32,
    pub auto_shifter_on:i32,
    pub ride_height:[f32;2],
    pub turbo_boost:f32,
    pub ballast:f32,
    pub air_density:f32,
    pub air_temp:f32,
    pub road_temp:f32,
    pub local_angular_vel:[f32;3],
    pub final_ff:f32,
    pub performance_meter:f32,

    pub engine_brake:i32,
    pub ers_recovery_level:i32,
    pub ers_power_level:i32,
    pub ers_heat_charging:i32,
    pub ers_is_charging:i32,
    pub kers_current_kj:f32,

    pub drs_availabel:i32,
    pub drs_enabled:i32,

    pub breake_temp:[f32;4],
    pub clutch:f32,

    pub tyre_temp_i:[f32;4],
    pub tyre_temp_m:[f32;4],
    pub tyre_temp_o:[f32;4],
    pub us_ai_controlled:i32,
    pub tyre_contact_point:[[f32;3];4],
    pub tyre_contact_normal:[[f32;3];4],
    pub tyre_contact_heading:[[f32;3];4],
    
    pub brake_bias:f32,
    
    pub local_velocity:[f32;3],

    pub p2p_activations:i32,
    pub p2p_status:i32,

    pub current_max_rpm:i32,

    pub mz:[f32;4],
    pub fx:[f32;4],
    pub fy:[f32;4],
    pub slip_ratio:[f32;4],
    pub slip_angle:[f32;4],

    pub tc_in_action:i32,
    pub abs_in_action:i32,
    pub suspension_damage:[f32;4],
    pub tyre_temp:[f32;4]
}

#[derive(Clone)]
pub struct SPageFileGraphic{
    pub packet_id:i32,
    pub status:i32,
    pub session:i32,
    pub current_time:[char;15],
    pub last_time:[char;15],
    pub best_time:[char;15],
    pub split:[char;15],
    pub completed_laps:i32,
    pub position:i32,
    pub i_current_time:i32,
    pub i_last_time:i32,
    pub i_best_time:i32,
    pub session_time_left:f32,
    pub distance_traveled:f32,
    pub is_in_pit:i32,
    pub current_sector_index:i32,
    pub last_sector_time:i32,
    pub number_of_laps:i32,
    pub tyre_compound:[char;33],
    pub replay_time_multiplier:f32,
    pub normalized_car_position:f32,

    pub actie_cars:i32,
    pub car_coordinates:[[f32;3];60],
    pub car_id:[i32;60],
    pub player_car_id:i32,
    pub penality_time:f32,
    pub flag:i32,
    pub penalty:i32,
    pub ideal_line_on:i32,
    pub is_in_pit_lane:i32,

    pub surface_grip:f32,
    pub mandatory_pit_done:i32,

    pub wind_speed:f32,
    pub wind_direction:f32,

    pub is_setup_menu_visible:i32,

    pub main_display_index:i32,
    pub secondary_display_index:i32,
    pub tc:i32,
    pub tc_cut:i32,
    pub engine_map:i32,
    pub abs:i32,
    pub fuel_x_lap:i32,
    pub rain_lights:i32,
    pub flashing_lights:i32,
    pub lights_stage:i32,
    pub exhaust_temperature:f32,
    pub wiper_lv:i32,
    pub driver_stint_total_time_left:i32,
    pub driver_stint_time_left:i32,
    pub rain_tyres:i32
}