/**
 * @file ExceptionTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef ____
#define ____
#pragma once

#include <exception>
#include <string>

namespace DogGE{
    namespace F1_2022{
        class ValidationException:public std::exception{
            private:
            std::string message;
            public:
            ValidationException();
            
            virtual const char* what() const throw();
        };
    }
}
#endif                                