/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __CAR_DAMAGE_DATA__
#define __CAR_DAMAGE_DATA__
#pragma once

#include <stdint.h>


namespace DogGE{
    namespace F1_2021{
        class CarDamageData{
            private:
            float tyresWearRL;
float tyresWearRR;
float tyresWearFL;
float tyresWearFR;
uint8_t tyresDamageRL;
uint8_t tyresDamageRR;
uint8_t tyresDamageFL;
uint8_t tyresDamageFR;
uint8_t brakesDamageRL;
uint8_t brakesDamageRR;
uint8_t brakesDamageFL;
uint8_t brakesDamageFR;
uint8_t frontLeftWingDamage;
uint8_t frontRightWingDamage;
uint8_t rearWingDamage;
uint8_t floorDamage;
uint8_t diffuserDamage;
uint8_t sidepodDamage;
uint8_t drsFault;
uint8_t gearBoxDamage;
uint8_t engineDamage;
uint8_t engineMGUHWear;
uint8_t engineESWear;
uint8_t engineCEWear;
uint8_t engineICEWear;
uint8_t engineMGUKWear;
uint8_t engineTCWear;

            public:
            void setTyresWearRL(float tyresWearRL);
void setTyresWearRR(float tyresWearRR);
void setTyresWearFL(float tyresWearFL);
void setTyresWearFR(float tyresWearFR);
void setTyresDamageRL(uint8_t tyresDamageRL);
void setTyresDamageRR(uint8_t tyresDamageRR);
void setTyresDamageFL(uint8_t tyresDamageFL);
void setTyresDamageFR(uint8_t tyresDamageFR);
void setBrakesDamageRL(uint8_t brakesDamageRL);
void setBrakesDamageRR(uint8_t brakesDamageRR);
void setBrakesDamageFL(uint8_t brakesDamageFL);
void setBrakesDamageFR(uint8_t brakesDamageFR);
void setFrontLeftWingDamage(uint8_t frontLeftWingDamage);
void setFrontRightWingDamage(uint8_t frontRightWingDamage);
void setRearWingDamage(uint8_t rearWingDamage);
void setFloorDamage(uint8_t floorDamage);
void setDiffuserDamage(uint8_t diffuserDamage);
void setSidepodDamage(uint8_t sidepodDamage);
void setDrsFault(uint8_t drsFault);
void setGearBoxDamage(uint8_t gearBoxDamage);
void setEngineDamage(uint8_t engineDamage);
void setEngineMGUHWear(uint8_t engineMGUHWear);
void setEngineESWear(uint8_t engineESWear);
void setEngineCEWear(uint8_t engineCEWear);
void setEngineICEWear(uint8_t engineICEWear);
void setEngineMGUKWear(uint8_t engineMGUKWear);
void setEngineTCWear(uint8_t engineTCWear);

            float getTyresWearRL();
float getTyresWearRR();
float getTyresWearFL();
float getTyresWearFR();
uint8_t getTyresDamageRL();
uint8_t getTyresDamageRR();
uint8_t getTyresDamageFL();
uint8_t getTyresDamageFR();
uint8_t getBrakesDamageRL();
uint8_t getBrakesDamageRR();
uint8_t getBrakesDamageFL();
uint8_t getBrakesDamageFR();
uint8_t getFrontLeftWingDamage();
uint8_t getFrontRightWingDamage();
uint8_t getRearWingDamage();
uint8_t getFloorDamage();
uint8_t getDiffuserDamage();
uint8_t getSidepodDamage();
uint8_t getDrsFault();
uint8_t getGearBoxDamage();
uint8_t getEngineDamage();
uint8_t getEngineMGUHWear();
uint8_t getEngineESWear();
uint8_t getEngineCEWear();
uint8_t getEngineICEWear();
uint8_t getEngineMGUKWear();
uint8_t getEngineTCWear();

        };
    }
}

#endif                                