/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __CAR_MOTION_DATA__
#define __CAR_MOTION_DATA__
#pragma once

#include <stdint.h>


namespace DogGE{
    namespace F1_2021{
        class CarMotionData{
            private:
            float worldPositionX;
float worldPositionY;
float worldPositionZ;
float worldVelocityX;
float worldVelocityY;
float worldVelocityZ;
int16_t worldForwardDirX;
int16_t worldForwardDirY;
int16_t worldForwardDirZ;
int16_t worldRightDirX;
int16_t worldRightDirY;
int16_t worldRightDirZ;
float gForceLateral;
float gForceLongitudinal;
float gForceVertical;
float yaw;
float pitch;
float roll;

            public:
            void setWorldPositionX(float worldPositionX);
void setWorldPositionY(float worldPositionY);
void setWorldPositionZ(float worldPositionZ);
void setWorldVelocityX(float worldVelocityX);
void setWorldVelocityY(float worldVelocityY);
void setWorldVelocityZ(float worldVelocityZ);
void setWorldForwardDirX(int16_t worldForwardDirX);
void setWorldForwardDirY(int16_t worldForwardDirY);
void setWorldForwardDirZ(int16_t worldForwardDirZ);
void setWorldRightDirX(int16_t worldRightDirX);
void setWorldRightDirY(int16_t worldRightDirY);
void setWorldRightDirZ(int16_t worldRightDirZ);
void setGForceLateral(float gForceLateral);
void setGForceLongitudinal(float gForceLongitudinal);
void setGForceVertical(float gForceVertical);
void setYaw(float yaw);
void setPitch(float pitch);
void setRoll(float roll);

            float getWorldPositionX();
float getWorldPositionY();
float getWorldPositionZ();
float getWorldVelocityX();
float getWorldVelocityY();
float getWorldVelocityZ();
int16_t getWorldForwardDirX();
int16_t getWorldForwardDirY();
int16_t getWorldForwardDirZ();
int16_t getWorldRightDirX();
int16_t getWorldRightDirY();
int16_t getWorldRightDirZ();
float getGForceLateral();
float getGForceLongitudinal();
float getGForceVertical();
float getYaw();
float getPitch();
float getRoll();

        };
    }
}

#endif                                