/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __CAR_SETUPS_PACKAGE__
#define __CAR_SETUPS_PACKAGE__
#pragma once

#include <stdint.h>
#include <DataClass/Header.h>
#include <DataClass/CarSetupData.h>


namespace DogGE{
    namespace F1_2021{
        class CarSetupsPackage{
            private:
            Header header;
CarSetupData carSetups[22];

            public:
            void setHeader(Header header);
void setCarSetups(CarSetupData* carSetups);

            Header getHeader();
CarSetupData* getCarSetups();

        };
    }
}

#endif                                