/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __FINAL_CLASSIFICATION_DATA__
#define __FINAL_CLASSIFICATION_DATA__
#pragma once

#include <stdint.h>


namespace DogGE{
    namespace F1_2021{
        class FinalClassificationData{
            private:
            uint8_t position;
uint8_t numLaps;
uint8_t gridPosition;
uint8_t points;
uint8_t numPitStops;
uint8_t resultStatus;
uint32_t bestLapTimeInMs;
double totalRaceTime;
uint8_t penaltiesTime;
uint8_t numPenalties;
uint8_t numTyreStints;
uint8_t tyreStintsActual[8];
uint8_t tyreStintsVisual[8];

            public:
            void setPosition(uint8_t position);
void setNumLaps(uint8_t numLaps);
void setGridPosition(uint8_t gridPosition);
void setPoints(uint8_t points);
void setNumPitStops(uint8_t numPitStops);
void setResultStatus(uint8_t resultStatus);
void setBestLapTimeInMs(uint32_t bestLapTimeInMs);
void setTotalRaceTime(double totalRaceTime);
void setPenaltiesTime(uint8_t penaltiesTime);
void setNumPenalties(uint8_t numPenalties);
void setNumTyreStints(uint8_t numTyreStints);
void setTyreStintsActual(uint8_t* tyreStintsActual);
void setTyreStintsVisual(uint8_t* tyreStintsVisual);

            uint8_t getPosition();
uint8_t getNumLaps();
uint8_t getGridPosition();
uint8_t getPoints();
uint8_t getNumPitStops();
uint8_t getResultStatus();
uint32_t getBestLapTimeInMs();
double getTotalRaceTime();
uint8_t getPenaltiesTime();
uint8_t getNumPenalties();
uint8_t getNumTyreStints();
uint8_t* getTyreStintsActual();
uint8_t* getTyreStintsVisual();

        };
    }
}

#endif                                