/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __LOBBY_INFO_DATA__
#define __LOBBY_INFO_DATA__
#pragma once

#include <stdint.h>


namespace DogGE{
    namespace F1_2021{
        class LobbyInfoData{
            private:
            uint8_t aiControlled;
uint8_t teamId;
uint8_t nationality;
char name[48];
uint8_t carNumber;
uint8_t readyStatus;

            public:
            void setAiControlled(uint8_t aiControlled);
void setTeamId(uint8_t teamId);
void setNationality(uint8_t nationality);
void setName(char* name);
void setCarNumber(uint8_t carNumber);
void setReadyStatus(uint8_t readyStatus);

            uint8_t getAiControlled();
uint8_t getTeamId();
uint8_t getNationality();
char* getName();
uint8_t getCarNumber();
uint8_t getReadyStatus();

        };
    }
}

#endif                                