/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __PARTICIPANTS_DATA__
#define __PARTICIPANTS_DATA__
#pragma once

#include <stdint.h>


namespace DogGE{
    namespace F1_2021{
        class ParticipantsData{
            private:
            uint8_t aiControlled;
uint8_t driverId;
uint8_t networkId;
uint8_t teamId;
uint8_t myTeam;
uint8_t raceNumer;
uint8_t nationality;
char name[48];
uint8_t yourTelemetry;

            public:
            void setAiControlled(uint8_t aiControlled);
void setDriverId(uint8_t driverId);
void setNetworkId(uint8_t networkId);
void setTeamId(uint8_t teamId);
void setMyTeam(uint8_t myTeam);
void setRaceNumer(uint8_t raceNumer);
void setNationality(uint8_t nationality);
void setName(char* name);
void setYourTelemetry(uint8_t yourTelemetry);

            uint8_t getAiControlled();
uint8_t getDriverId();
uint8_t getNetworkId();
uint8_t getTeamId();
uint8_t getMyTeam();
uint8_t getRaceNumer();
uint8_t getNationality();
char* getName();
uint8_t getYourTelemetry();

        };
    }
}

#endif                                