/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/CarDamageData.h>

namespace DogGE{
    namespace F1_2021{
        float CarDamageData::getTyresWearRL(){return this->tyresWearRL;}
float CarDamageData::getTyresWearRR(){return this->tyresWearRR;}
float CarDamageData::getTyresWearFL(){return this->tyresWearFL;}
float CarDamageData::getTyresWearFR(){return this->tyresWearFR;}
uint8_t CarDamageData::getTyresDamageRL(){return this->tyresDamageRL;}
uint8_t CarDamageData::getTyresDamageRR(){return this->tyresDamageRR;}
uint8_t CarDamageData::getTyresDamageFL(){return this->tyresDamageFL;}
uint8_t CarDamageData::getTyresDamageFR(){return this->tyresDamageFR;}
uint8_t CarDamageData::getBrakesDamageRL(){return this->brakesDamageRL;}
uint8_t CarDamageData::getBrakesDamageRR(){return this->brakesDamageRR;}
uint8_t CarDamageData::getBrakesDamageFL(){return this->brakesDamageFL;}
uint8_t CarDamageData::getBrakesDamageFR(){return this->brakesDamageFR;}
uint8_t CarDamageData::getFrontLeftWingDamage(){return this->frontLeftWingDamage;}
uint8_t CarDamageData::getFrontRightWingDamage(){return this->frontRightWingDamage;}
uint8_t CarDamageData::getRearWingDamage(){return this->rearWingDamage;}
uint8_t CarDamageData::getFloorDamage(){return this->floorDamage;}
uint8_t CarDamageData::getDiffuserDamage(){return this->diffuserDamage;}
uint8_t CarDamageData::getSidepodDamage(){return this->sidepodDamage;}
uint8_t CarDamageData::getDrsFault(){return this->drsFault;}
uint8_t CarDamageData::getGearBoxDamage(){return this->gearBoxDamage;}
uint8_t CarDamageData::getEngineDamage(){return this->engineDamage;}
uint8_t CarDamageData::getEngineMGUHWear(){return this->engineMGUHWear;}
uint8_t CarDamageData::getEngineESWear(){return this->engineESWear;}
uint8_t CarDamageData::getEngineCEWear(){return this->engineCEWear;}
uint8_t CarDamageData::getEngineICEWear(){return this->engineICEWear;}
uint8_t CarDamageData::getEngineMGUKWear(){return this->engineMGUKWear;}
uint8_t CarDamageData::getEngineTCWear(){return this->engineTCWear;}

        void CarDamageData::setTyresWearRL(float tyresWearRL){this->tyresWearRL = tyresWearRL;}
void CarDamageData::setTyresWearRR(float tyresWearRR){this->tyresWearRR = tyresWearRR;}
void CarDamageData::setTyresWearFL(float tyresWearFL){this->tyresWearFL = tyresWearFL;}
void CarDamageData::setTyresWearFR(float tyresWearFR){this->tyresWearFR = tyresWearFR;}
void CarDamageData::setTyresDamageRL(uint8_t tyresDamageRL){this->tyresDamageRL = tyresDamageRL;}
void CarDamageData::setTyresDamageRR(uint8_t tyresDamageRR){this->tyresDamageRR = tyresDamageRR;}
void CarDamageData::setTyresDamageFL(uint8_t tyresDamageFL){this->tyresDamageFL = tyresDamageFL;}
void CarDamageData::setTyresDamageFR(uint8_t tyresDamageFR){this->tyresDamageFR = tyresDamageFR;}
void CarDamageData::setBrakesDamageRL(uint8_t brakesDamageRL){this->brakesDamageRL = brakesDamageRL;}
void CarDamageData::setBrakesDamageRR(uint8_t brakesDamageRR){this->brakesDamageRR = brakesDamageRR;}
void CarDamageData::setBrakesDamageFL(uint8_t brakesDamageFL){this->brakesDamageFL = brakesDamageFL;}
void CarDamageData::setBrakesDamageFR(uint8_t brakesDamageFR){this->brakesDamageFR = brakesDamageFR;}
void CarDamageData::setFrontLeftWingDamage(uint8_t frontLeftWingDamage){this->frontLeftWingDamage = frontLeftWingDamage;}
void CarDamageData::setFrontRightWingDamage(uint8_t frontRightWingDamage){this->frontRightWingDamage = frontRightWingDamage;}
void CarDamageData::setRearWingDamage(uint8_t rearWingDamage){this->rearWingDamage = rearWingDamage;}
void CarDamageData::setFloorDamage(uint8_t floorDamage){this->floorDamage = floorDamage;}
void CarDamageData::setDiffuserDamage(uint8_t diffuserDamage){this->diffuserDamage = diffuserDamage;}
void CarDamageData::setSidepodDamage(uint8_t sidepodDamage){this->sidepodDamage = sidepodDamage;}
void CarDamageData::setDrsFault(uint8_t drsFault){this->drsFault = drsFault;}
void CarDamageData::setGearBoxDamage(uint8_t gearBoxDamage){this->gearBoxDamage = gearBoxDamage;}
void CarDamageData::setEngineDamage(uint8_t engineDamage){this->engineDamage = engineDamage;}
void CarDamageData::setEngineMGUHWear(uint8_t engineMGUHWear){this->engineMGUHWear = engineMGUHWear;}
void CarDamageData::setEngineESWear(uint8_t engineESWear){this->engineESWear = engineESWear;}
void CarDamageData::setEngineCEWear(uint8_t engineCEWear){this->engineCEWear = engineCEWear;}
void CarDamageData::setEngineICEWear(uint8_t engineICEWear){this->engineICEWear = engineICEWear;}
void CarDamageData::setEngineMGUKWear(uint8_t engineMGUKWear){this->engineMGUKWear = engineMGUKWear;}
void CarDamageData::setEngineTCWear(uint8_t engineTCWear){this->engineTCWear = engineTCWear;}

    }
}                    