/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/CarTelemetryData.h>

namespace DogGE{
    namespace F1_2021{
        uint16_t CarTelemetryData::getSpeed(){return this->speed;}
float CarTelemetryData::getThrottle(){return this->throttle;}
float CarTelemetryData::getSteer(){return this->steer;}
float CarTelemetryData::getBrake(){return this->brake;}
uint8_t CarTelemetryData::getClutch(){return this->clutch;}
int8_t CarTelemetryData::getGear(){return this->gear;}
uint16_t CarTelemetryData::getEngineRPM(){return this->engineRPM;}
uint8_t CarTelemetryData::getDrs(){return this->drs;}
uint8_t CarTelemetryData::getRevLightsPercent(){return this->revLightsPercent;}
uint16_t CarTelemetryData::getRevLightsBitValue(){return this->revLightsBitValue;}
uint16_t CarTelemetryData::getBrakesTemperatureRL(){return this->brakesTemperatureRL;}
uint16_t CarTelemetryData::getBrakesTemperatureRR(){return this->brakesTemperatureRR;}
uint16_t CarTelemetryData::getBrakesTemperatureFL(){return this->brakesTemperatureFL;}
uint16_t CarTelemetryData::getBrakesTemperatureFR(){return this->brakesTemperatureFR;}
uint8_t CarTelemetryData::getTyreSurfaceTemperatureRL(){return this->tyreSurfaceTemperatureRL;}
uint8_t CarTelemetryData::getTyreSurfaceTemperatureRR(){return this->tyreSurfaceTemperatureRR;}
uint8_t CarTelemetryData::getTyreSurfaceTemperatureFL(){return this->tyreSurfaceTemperatureFL;}
uint8_t CarTelemetryData::getTyreSurfaceTemperatureFR(){return this->tyreSurfaceTemperatureFR;}
uint8_t CarTelemetryData::getTyreInnerTemperatureRL(){return this->tyreInnerTemperatureRL;}
uint8_t CarTelemetryData::getTyreInnerTemperatureRR(){return this->tyreInnerTemperatureRR;}
uint8_t CarTelemetryData::getTyreInnerTemperatureFL(){return this->tyreInnerTemperatureFL;}
uint8_t CarTelemetryData::getTyreInnerTemperatureFR(){return this->tyreInnerTemperatureFR;}
uint16_t CarTelemetryData::getEngineTemperature(){return this->engineTemperature;}
float CarTelemetryData::getTyresPressureRL(){return this->tyresPressureRL;}
float CarTelemetryData::getTyresPressureRR(){return this->tyresPressureRR;}
float CarTelemetryData::getTyresPressureFL(){return this->tyresPressureFL;}
float CarTelemetryData::getTyresPressureFR(){return this->tyresPressureFR;}
uint8_t CarTelemetryData::getSurfaceTypeRL(){return this->surfaceTypeRL;}
uint8_t CarTelemetryData::getSurfaceTypeRR(){return this->surfaceTypeRR;}
uint8_t CarTelemetryData::getSurfaceTypeFL(){return this->surfaceTypeFL;}
uint8_t CarTelemetryData::getSurfaceTypeFR(){return this->surfaceTypeFR;}

        void CarTelemetryData::setSpeed(uint16_t speed){this->speed = speed;}
void CarTelemetryData::setThrottle(float throttle){this->throttle = throttle;}
void CarTelemetryData::setSteer(float steer){this->steer = steer;}
void CarTelemetryData::setBrake(float brake){this->brake = brake;}
void CarTelemetryData::setClutch(uint8_t clutch){this->clutch = clutch;}
void CarTelemetryData::setGear(int8_t gear){this->gear = gear;}
void CarTelemetryData::setEngineRPM(uint16_t engineRPM){this->engineRPM = engineRPM;}
void CarTelemetryData::setDrs(uint8_t drs){this->drs = drs;}
void CarTelemetryData::setRevLightsPercent(uint8_t revLightsPercent){this->revLightsPercent = revLightsPercent;}
void CarTelemetryData::setRevLightsBitValue(uint16_t revLightsBitValue){this->revLightsBitValue = revLightsBitValue;}
void CarTelemetryData::setBrakesTemperatureRL(uint16_t brakesTemperatureRL){this->brakesTemperatureRL = brakesTemperatureRL;}
void CarTelemetryData::setBrakesTemperatureRR(uint16_t brakesTemperatureRR){this->brakesTemperatureRR = brakesTemperatureRR;}
void CarTelemetryData::setBrakesTemperatureFL(uint16_t brakesTemperatureFL){this->brakesTemperatureFL = brakesTemperatureFL;}
void CarTelemetryData::setBrakesTemperatureFR(uint16_t brakesTemperatureFR){this->brakesTemperatureFR = brakesTemperatureFR;}
void CarTelemetryData::setTyreSurfaceTemperatureRL(uint8_t tyreSurfaceTemperatureRL){this->tyreSurfaceTemperatureRL = tyreSurfaceTemperatureRL;}
void CarTelemetryData::setTyreSurfaceTemperatureRR(uint8_t tyreSurfaceTemperatureRR){this->tyreSurfaceTemperatureRR = tyreSurfaceTemperatureRR;}
void CarTelemetryData::setTyreSurfaceTemperatureFL(uint8_t tyreSurfaceTemperatureFL){this->tyreSurfaceTemperatureFL = tyreSurfaceTemperatureFL;}
void CarTelemetryData::setTyreSurfaceTemperatureFR(uint8_t tyreSurfaceTemperatureFR){this->tyreSurfaceTemperatureFR = tyreSurfaceTemperatureFR;}
void CarTelemetryData::setTyreInnerTemperatureRL(uint8_t tyreInnerTemperatureRL){this->tyreInnerTemperatureRL = tyreInnerTemperatureRL;}
void CarTelemetryData::setTyreInnerTemperatureRR(uint8_t tyreInnerTemperatureRR){this->tyreInnerTemperatureRR = tyreInnerTemperatureRR;}
void CarTelemetryData::setTyreInnerTemperatureFL(uint8_t tyreInnerTemperatureFL){this->tyreInnerTemperatureFL = tyreInnerTemperatureFL;}
void CarTelemetryData::setTyreInnerTemperatureFR(uint8_t tyreInnerTemperatureFR){this->tyreInnerTemperatureFR = tyreInnerTemperatureFR;}
void CarTelemetryData::setEngineTemperature(uint16_t engineTemperature){this->engineTemperature = engineTemperature;}
void CarTelemetryData::setTyresPressureRL(float tyresPressureRL){this->tyresPressureRL = tyresPressureRL;}
void CarTelemetryData::setTyresPressureRR(float tyresPressureRR){this->tyresPressureRR = tyresPressureRR;}
void CarTelemetryData::setTyresPressureFL(float tyresPressureFL){this->tyresPressureFL = tyresPressureFL;}
void CarTelemetryData::setTyresPressureFR(float tyresPressureFR){this->tyresPressureFR = tyresPressureFR;}
void CarTelemetryData::setSurfaceTypeRL(uint8_t surfaceTypeRL){this->surfaceTypeRL = surfaceTypeRL;}
void CarTelemetryData::setSurfaceTypeRR(uint8_t surfaceTypeRR){this->surfaceTypeRR = surfaceTypeRR;}
void CarTelemetryData::setSurfaceTypeFL(uint8_t surfaceTypeFL){this->surfaceTypeFL = surfaceTypeFL;}
void CarTelemetryData::setSurfaceTypeFR(uint8_t surfaceTypeFR){this->surfaceTypeFR = surfaceTypeFR;}

    }
}                    