/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/FinalClassificationPackage.h>

namespace DogGE{
    namespace F1_2021{
        Header FinalClassificationPackage::getHeader(){return this->header;}
uint8_t FinalClassificationPackage::getNumCars(){return this->numCars;}
FinalClassificationData* FinalClassificationPackage::getClassification(){return this->classification;}

        void FinalClassificationPackage::setHeader(Header header){this->header = header;}
void FinalClassificationPackage::setNumCars(uint8_t numCars){this->numCars = numCars;}
void FinalClassificationPackage::setClassification(FinalClassificationData* classification){for(int i=0;i<22;i++){
this->classification[i] = classification[i];
}
}

    }
}                    