/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/Header.h>

namespace DogGE{
    namespace F1_2021{
        uint16_t Header::getPacketFormat(){return this->packetFormat;}
uint8_t Header::getGameMajorVersion(){return this->gameMajorVersion;}
uint8_t Header::getGameMinorVersion(){return this->gameMinorVersion;}
uint8_t Header::getPacketVersion(){return this->packetVersion;}
uint8_t Header::getPacketId(){return this->packetId;}
uint64_t Header::getSessionUID(){return this->sessionUID;}
float Header::getSessionTime(){return this->sessionTime;}
uint32_t Header::getFrameIdentifier(){return this->frameIdentifier;}
uint8_t Header::getPlayerCarIndex(){return this->playerCarIndex;}
uint8_t Header::getSecondaryPlayerCarIndex(){return this->secondaryPlayerCarIndex;}

        void Header::setPacketFormat(uint16_t packetFormat){this->packetFormat = packetFormat;}
void Header::setGameMajorVersion(uint8_t gameMajorVersion){this->gameMajorVersion = gameMajorVersion;}
void Header::setGameMinorVersion(uint8_t gameMinorVersion){this->gameMinorVersion = gameMinorVersion;}
void Header::setPacketVersion(uint8_t packetVersion){this->packetVersion = packetVersion;}
void Header::setPacketId(uint8_t packetId){this->packetId = packetId;}
void Header::setSessionUID(uint64_t sessionUID){this->sessionUID = sessionUID;}
void Header::setSessionTime(float sessionTime){this->sessionTime = sessionTime;}
void Header::setFrameIdentifier(uint32_t frameIdentifier){this->frameIdentifier = frameIdentifier;}
void Header::setPlayerCarIndex(uint8_t playerCarIndex){this->playerCarIndex = playerCarIndex;}
void Header::setSecondaryPlayerCarIndex(uint8_t secondaryPlayerCarIndex){this->secondaryPlayerCarIndex = secondaryPlayerCarIndex;}

    }
}                    