/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/LapDataPackage.h>

namespace DogGE{
    namespace F1_2021{
        Header LapDataPackage::getHeader(){return this->header;}
LapData* LapDataPackage::getLapData(){return this->lapData;}

        void LapDataPackage::setHeader(Header header){this->header = header;}
void LapDataPackage::setLapData(LapData* lapData){for(int i=0;i<22;i++){
this->lapData[i] = lapData[i];
}
}

    }
}                    