/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/LobbyInfoData.h>

namespace DogGE{
    namespace F1_2021{
        uint8_t LobbyInfoData::getAiControlled(){return this->aiControlled;}
uint8_t LobbyInfoData::getTeamId(){return this->teamId;}
uint8_t LobbyInfoData::getNationality(){return this->nationality;}
char* LobbyInfoData::getName(){return this->name;}
uint8_t LobbyInfoData::getCarNumber(){return this->carNumber;}
uint8_t LobbyInfoData::getReadyStatus(){return this->readyStatus;}

        void LobbyInfoData::setAiControlled(uint8_t aiControlled){this->aiControlled = aiControlled;}
void LobbyInfoData::setTeamId(uint8_t teamId){this->teamId = teamId;}
void LobbyInfoData::setNationality(uint8_t nationality){this->nationality = nationality;}
void LobbyInfoData::setName(char* name){for(int i=0;i<48;i++){
this->name[i] = name[i];
}
}
void LobbyInfoData::setCarNumber(uint8_t carNumber){this->carNumber = carNumber;}
void LobbyInfoData::setReadyStatus(uint8_t readyStatus){this->readyStatus = readyStatus;}

    }
}                    