/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/MotionPackage.h>

namespace DogGE{
    namespace F1_2021{
        Header MotionPackage::getHeader(){return this->header;}
CarMotionData* MotionPackage::getCarMotionData(){return this->carMotionData;}
float* MotionPackage::getSuspensionPosition(){return this->suspensionPosition;}
float* MotionPackage::getSuspensionVelocity(){return this->suspensionVelocity;}
float* MotionPackage::getSuspensionAcceleration(){return this->suspensionAcceleration;}
float* MotionPackage::getWheelSpeed(){return this->wheelSpeed;}
float* MotionPackage::getWheelSlip(){return this->wheelSlip;}
float MotionPackage::getLocalVelocityX(){return this->localVelocityX;}
float MotionPackage::getLocalVelocityY(){return this->localVelocityY;}
float MotionPackage::getLocalVelocityZ(){return this->localVelocityZ;}
float MotionPackage::getAngularVelocityX(){return this->angularVelocityX;}
float MotionPackage::getAngularVelocityY(){return this->angularVelocityY;}
float MotionPackage::getAngularVelocityZ(){return this->angularVelocityZ;}
float MotionPackage::getAngularAccelerationX(){return this->angularAccelerationX;}
float MotionPackage::getAngularAccelerationY(){return this->angularAccelerationY;}
float MotionPackage::getAngularAccelerationZ(){return this->angularAccelerationZ;}
float MotionPackage::getFrontWheelsAngle(){return this->frontWheelsAngle;}

        void MotionPackage::setHeader(Header header){this->header = header;}
void MotionPackage::setCarMotionData(CarMotionData* carMotionData){for(int i=0;i<22;i++){
this->carMotionData[i] = carMotionData[i];
}
}
void MotionPackage::setSuspensionPosition(float* suspensionPosition){for(int i=0;i<4;i++){
this->suspensionPosition[i] = suspensionPosition[i];
}
}
void MotionPackage::setSuspensionVelocity(float* suspensionVelocity){for(int i=0;i<4;i++){
this->suspensionVelocity[i] = suspensionVelocity[i];
}
}
void MotionPackage::setSuspensionAcceleration(float* suspensionAcceleration){for(int i=0;i<4;i++){
this->suspensionAcceleration[i] = suspensionAcceleration[i];
}
}
void MotionPackage::setWheelSpeed(float* wheelSpeed){for(int i=0;i<4;i++){
this->wheelSpeed[i] = wheelSpeed[i];
}
}
void MotionPackage::setWheelSlip(float* wheelSlip){for(int i=0;i<4;i++){
this->wheelSlip[i] = wheelSlip[i];
}
}
void MotionPackage::setLocalVelocityX(float localVelocityX){this->localVelocityX = localVelocityX;}
void MotionPackage::setLocalVelocityY(float localVelocityY){this->localVelocityY = localVelocityY;}
void MotionPackage::setLocalVelocityZ(float localVelocityZ){this->localVelocityZ = localVelocityZ;}
void MotionPackage::setAngularVelocityX(float angularVelocityX){this->angularVelocityX = angularVelocityX;}
void MotionPackage::setAngularVelocityY(float angularVelocityY){this->angularVelocityY = angularVelocityY;}
void MotionPackage::setAngularVelocityZ(float angularVelocityZ){this->angularVelocityZ = angularVelocityZ;}
void MotionPackage::setAngularAccelerationX(float angularAccelerationX){this->angularAccelerationX = angularAccelerationX;}
void MotionPackage::setAngularAccelerationY(float angularAccelerationY){this->angularAccelerationY = angularAccelerationY;}
void MotionPackage::setAngularAccelerationZ(float angularAccelerationZ){this->angularAccelerationZ = angularAccelerationZ;}
void MotionPackage::setFrontWheelsAngle(float frontWheelsAngle){this->frontWheelsAngle = frontWheelsAngle;}

    }
}                    