/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/ParticipantsData.h>

namespace DogGE{
    namespace F1_2021{
        uint8_t ParticipantsData::getAiControlled(){return this->aiControlled;}
uint8_t ParticipantsData::getDriverId(){return this->driverId;}
uint8_t ParticipantsData::getNetworkId(){return this->networkId;}
uint8_t ParticipantsData::getTeamId(){return this->teamId;}
uint8_t ParticipantsData::getMyTeam(){return this->myTeam;}
uint8_t ParticipantsData::getRaceNumer(){return this->raceNumer;}
uint8_t ParticipantsData::getNationality(){return this->nationality;}
char* ParticipantsData::getName(){return this->name;}
uint8_t ParticipantsData::getYourTelemetry(){return this->yourTelemetry;}

        void ParticipantsData::setAiControlled(uint8_t aiControlled){this->aiControlled = aiControlled;}
void ParticipantsData::setDriverId(uint8_t driverId){this->driverId = driverId;}
void ParticipantsData::setNetworkId(uint8_t networkId){this->networkId = networkId;}
void ParticipantsData::setTeamId(uint8_t teamId){this->teamId = teamId;}
void ParticipantsData::setMyTeam(uint8_t myTeam){this->myTeam = myTeam;}
void ParticipantsData::setRaceNumer(uint8_t raceNumer){this->raceNumer = raceNumer;}
void ParticipantsData::setNationality(uint8_t nationality){this->nationality = nationality;}
void ParticipantsData::setName(char* name){for(int i=0;i<48;i++){
this->name[i] = name[i];
}
}
void ParticipantsData::setYourTelemetry(uint8_t yourTelemetry){this->yourTelemetry = yourTelemetry;}

    }
}                    