/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/SessionHistoryPackage.h>

namespace DogGE{
    namespace F1_2021{
        Header SessionHistoryPackage::getHeader(){return this->header;}
uint8_t SessionHistoryPackage::getCarIdx(){return this->carIdx;}
uint8_t SessionHistoryPackage::getNumLaps(){return this->numLaps;}
uint8_t SessionHistoryPackage::getNumTyreStints(){return this->numTyreStints;}
uint8_t SessionHistoryPackage::getBestLapTimeLapNum(){return this->bestLapTimeLapNum;}
uint8_t SessionHistoryPackage::getBestSector1LapNum(){return this->bestSector1LapNum;}
uint8_t SessionHistoryPackage::getBestSector2LapNum(){return this->bestSector2LapNum;}
uint8_t SessionHistoryPackage::getBestSector3LapNum(){return this->bestSector3LapNum;}
LapHistoryData* SessionHistoryPackage::getLapHistoryData(){return this->lapHistoryData;}
TyreStintHistoryData* SessionHistoryPackage::getTyreStintsHistoryData(){return this->tyreStintsHistoryData;}

        void SessionHistoryPackage::setHeader(Header header){this->header = header;}
void SessionHistoryPackage::setCarIdx(uint8_t carIdx){this->carIdx = carIdx;}
void SessionHistoryPackage::setNumLaps(uint8_t numLaps){this->numLaps = numLaps;}
void SessionHistoryPackage::setNumTyreStints(uint8_t numTyreStints){this->numTyreStints = numTyreStints;}
void SessionHistoryPackage::setBestLapTimeLapNum(uint8_t bestLapTimeLapNum){this->bestLapTimeLapNum = bestLapTimeLapNum;}
void SessionHistoryPackage::setBestSector1LapNum(uint8_t bestSector1LapNum){this->bestSector1LapNum = bestSector1LapNum;}
void SessionHistoryPackage::setBestSector2LapNum(uint8_t bestSector2LapNum){this->bestSector2LapNum = bestSector2LapNum;}
void SessionHistoryPackage::setBestSector3LapNum(uint8_t bestSector3LapNum){this->bestSector3LapNum = bestSector3LapNum;}
void SessionHistoryPackage::setLapHistoryData(LapHistoryData* lapHistoryData){for(int i=0;i<100;i++){
this->lapHistoryData[i] = lapHistoryData[i];
}
}
void SessionHistoryPackage::setTyreStintsHistoryData(TyreStintHistoryData* tyreStintsHistoryData){for(int i=0;i<8;i++){
this->tyreStintsHistoryData[i] = tyreStintsHistoryData[i];
}
}

    }
}                    