/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/TyreStintHistoryData.h>

namespace DogGE{
    namespace F1_2021{
        uint8_t TyreStintHistoryData::getEndLap(){return this->endLap;}
uint8_t TyreStintHistoryData::getTyreActualCompound(){return this->tyreActualCompound;}
uint8_t TyreStintHistoryData::getTyreVisualCompound(){return this->tyreVisualCompound;}

        void TyreStintHistoryData::setEndLap(uint8_t endLap){this->endLap = endLap;}
void TyreStintHistoryData::setTyreActualCompound(uint8_t tyreActualCompound){this->tyreActualCompound = tyreActualCompound;}
void TyreStintHistoryData::setTyreVisualCompound(uint8_t tyreVisualCompound){this->tyreVisualCompound = tyreVisualCompound;}

    }
}                    