/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/WeatherForecastSample.h>

namespace DogGE{
    namespace F1_2021{
        uint8_t WeatherForecastSample::getSessionType(){return this->sessionType;}
uint8_t WeatherForecastSample::getTimeOffset(){return this->timeOffset;}
uint8_t WeatherForecastSample::getWeather(){return this->weather;}
int8_t WeatherForecastSample::getTrackTemperature(){return this->trackTemperature;}
int8_t WeatherForecastSample::getTrackTemperatureChange(){return this->trackTemperatureChange;}
int8_t WeatherForecastSample::getAirTemperature(){return this->airTemperature;}
int8_t WeatherForecastSample::getAirTemperatureChange(){return this->airTemperatureChange;}
uint8_t WeatherForecastSample::getRainPercentage(){return this->rainPercentage;}

        void WeatherForecastSample::setSessionType(uint8_t sessionType){this->sessionType = sessionType;}
void WeatherForecastSample::setTimeOffset(uint8_t timeOffset){this->timeOffset = timeOffset;}
void WeatherForecastSample::setWeather(uint8_t weather){this->weather = weather;}
void WeatherForecastSample::setTrackTemperature(int8_t trackTemperature){this->trackTemperature = trackTemperature;}
void WeatherForecastSample::setTrackTemperatureChange(int8_t trackTemperatureChange){this->trackTemperatureChange = trackTemperatureChange;}
void WeatherForecastSample::setAirTemperature(int8_t airTemperature){this->airTemperature = airTemperature;}
void WeatherForecastSample::setAirTemperatureChange(int8_t airTemperatureChange){this->airTemperatureChange = airTemperatureChange;}
void WeatherForecastSample::setRainPercentage(uint8_t rainPercentage){this->rainPercentage = rainPercentage;}

    }
}                    