/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef ____F1_DATA_ENTITY____
#define ____F1_DATA_ENTITY____
#pragma once

#include <stdint.h>
#include <AbstractEntity.h>



namespace DogGE{
    namespace F1_2021{
        class FinalClassificationDataEntity: public DogGE::Database::AbstractEntity{
            private:
            uint8_t position;
uint8_t numLaps;
uint8_t gridPosition;
uint8_t points;
uint8_t numPitStops;
uint8_t resultStatus;
uint32_t bestLapTimeInMs;
double totalRaceTime;
uint8_t penaltiesTime;
uint8_t numPenalties;
uint8_t numTyreStints;
uint8_t tyreStintsActual[8];
uint8_t tyreStintsVisual[8];

            public:
            

            void setPosition(uint8_t position);
void setNumLaps(uint8_t numLaps);
void setGridPosition(uint8_t gridPosition);
void setPoints(uint8_t points);
void setNumPitStops(uint8_t numPitStops);
void setResultStatus(uint8_t resultStatus);
void setBestLapTimeInMs(uint32_t bestLapTimeInMs);
void setTotalRaceTime(double totalRaceTime);
void setPenaltiesTime(uint8_t penaltiesTime);
void setNumPenalties(uint8_t numPenalties);
void setNumTyreStints(uint8_t numTyreStints);
void setTyreStintsActual(uint8_t* tyreStintsActual);
void setTyreStintsVisual(uint8_t* tyreStintsVisual);

            uint8_t getPosition();
uint8_t getNumLaps();
uint8_t getGridPosition();
uint8_t getPoints();
uint8_t getNumPitStops();
uint8_t getResultStatus();
uint32_t getBestLapTimeInMs();
double getTotalRaceTime();
uint8_t getPenaltiesTime();
uint8_t getNumPenalties();
uint8_t getNumTyreStints();
uint8_t* getTyreStintsActual();
uint8_t* getTyreStintsVisual();


            virtual std::string getTableName();
            virtual std::string getTableDefinition();
            
            virtual void matchIntData(std::string column,int data);
            virtual void matchInt64Data(std::string column,int64_t data);
            virtual void matchRealData(std::string column,float data);
            virtual void matchStringData(std::string column,std::string data);
            virtual void matchRawData(std::string column,char* data,int length);

            virtual std::map<std::string,int> getIntMap();
            virtual std::map<std::string,int64_t> getInt64Map();
            virtual std::map<std::string,float> getRealMap();
            virtual std::map<std::string,std::string> getStringMap();
            virtual std::map<std::string,std::pair<char*,int>> getRawMap();
        };
    }
}

#endif                                                   