/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef ____F1_DATA_ENTITY____
#define ____F1_DATA_ENTITY____
#pragma once

#include <stdint.h>
#include <AbstractEntity.h>



namespace DogGE{
    namespace F1_2021{
        class LapHistoryDataEntity: public DogGE::Database::AbstractEntity{
            private:
            uint32_t lapTimeInMS;
uint16_t sector1TimeInMs;
uint16_t sector2TimeInMs;
uint16_t sector3TimeInMs;
uint8_t lapValidBitFlags;

            public:
            

            void setLapTimeInMS(uint32_t lapTimeInMS);
void setSector1TimeInMs(uint16_t sector1TimeInMs);
void setSector2TimeInMs(uint16_t sector2TimeInMs);
void setSector3TimeInMs(uint16_t sector3TimeInMs);
void setLapValidBitFlags(uint8_t lapValidBitFlags);

            uint32_t getLapTimeInMS();
uint16_t getSector1TimeInMs();
uint16_t getSector2TimeInMs();
uint16_t getSector3TimeInMs();
uint8_t getLapValidBitFlags();


            virtual std::string getTableName();
            virtual std::string getTableDefinition();
            
            virtual void matchIntData(std::string column,int data);
            virtual void matchInt64Data(std::string column,int64_t data);
            virtual void matchRealData(std::string column,float data);
            virtual void matchStringData(std::string column,std::string data);
            virtual void matchRawData(std::string column,char* data,int length);

            virtual std::map<std::string,int> getIntMap();
            virtual std::map<std::string,int64_t> getInt64Map();
            virtual std::map<std::string,float> getRealMap();
            virtual std::map<std::string,std::string> getStringMap();
            virtual std::map<std::string,std::pair<char*,int>> getRawMap();
        };
    }
}

#endif                                                   