/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef ____F1_DATA_ENTITY____
#define ____F1_DATA_ENTITY____
#pragma once

#include <stdint.h>
#include <AbstractEntity.h>



namespace DogGE{
    namespace F1_2021{
        class ParticipantsDataEntity: public DogGE::Database::AbstractEntity{
            private:
            uint8_t aiControlled;
uint8_t driverId;
uint8_t networkId;
uint8_t teamId;
uint8_t myTeam;
uint8_t raceNumer;
uint8_t nationality;
char name[48];
uint8_t yourTelemetry;

            public:
            

            void setAiControlled(uint8_t aiControlled);
void setDriverId(uint8_t driverId);
void setNetworkId(uint8_t networkId);
void setTeamId(uint8_t teamId);
void setMyTeam(uint8_t myTeam);
void setRaceNumer(uint8_t raceNumer);
void setNationality(uint8_t nationality);
void setName(char* name);
void setYourTelemetry(uint8_t yourTelemetry);

            uint8_t getAiControlled();
uint8_t getDriverId();
uint8_t getNetworkId();
uint8_t getTeamId();
uint8_t getMyTeam();
uint8_t getRaceNumer();
uint8_t getNationality();
char* getName();
uint8_t getYourTelemetry();


            virtual std::string getTableName();
            virtual std::string getTableDefinition();
            
            virtual void matchIntData(std::string column,int data);
            virtual void matchInt64Data(std::string column,int64_t data);
            virtual void matchRealData(std::string column,float data);
            virtual void matchStringData(std::string column,std::string data);
            virtual void matchRawData(std::string column,char* data,int length);

            virtual std::map<std::string,int> getIntMap();
            virtual std::map<std::string,int64_t> getInt64Map();
            virtual std::map<std::string,float> getRealMap();
            virtual std::map<std::string,std::string> getStringMap();
            virtual std::map<std::string,std::pair<char*,int>> getRawMap();
        };
    }
}

#endif                                                   