/**
 * @file ExceptionTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __{{&DEFINE_NAME}}__
#define __{{&DEFINE_NAME}}__
#pragma once

#include <exception>
{{&INCLUDES}}

namespace DogGE{
    namespace {{&NAMESPACE_NAME}}{
        class {{&CLASS_NAME}}:public std::exception{
            private:
            {{&PROPERTIES}}
            public:
            {{&CLASS_NAME}}({{&CONSTRUCTOR_ARGS}});
            {{&GETTER_FUNCTION}}
            virtual const char* what() const throw();
        };
    }
}
#endif