/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <{{&INCLUDE_HEADER}}>

namespace DogGE{
    namespace {{&NAMESPACE_NAME}}{
        {{&GETTER_CODE}}
        {{&SETTER_CODE}}
    }
}