/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __{{&DEFINE_NAME}}__
#define __{{&DEFINE_NAME}}__
#pragma once

#include <stdint.h>
{{&INCLUDE_FILES}}

namespace DogGE{
    namespace {{&NAMESPACE_NAME}}{
        class {{&CLASS_NAME}}{
            private:
            {{&PROPERTIES}}
            public:
            {{&SETTERS_DEFINITION}}
            {{&GETTERS_DEFINITION}}
        };
    }
}

#endif