/**
 * @file RecorderTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 0.1
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <queue>
#include <mutex>
#include <Database.h>
#include <ProducerConsumerRecorder.h>
#include <RecordState.h>


namespace DogGE{
    namespace {{&NAMESPACE_NAME}}{
        class {{&CLASS_NAME}}:public CTelemetry::Recorder::ProducerConsumerRecorder{
            protected:
            DogGE::Database::Database* mDatabase;
            std::queue<std::array<char,2000>> mQueue;
            std::mutex mtx;
            int mRecivedPackages;
            int mParsedPackages;
            std::string mOutput;
            
            public:
            {{&CLASS_NAME}}();
            void setOutput(std::string output);
            virtual void init() override;
            virtual void producer()override;
            virtual void consumer()override;
            virtual CTelemetry::Recorder::RecordState getState() override;
        };
    }
}