/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __CAR_STATUS_PACKAGE__
#define __CAR_STATUS_PACKAGE__
#pragma once

#include <stdint.h>
#include <DataClass/Header.h>
#include <DataClass/CarStatusData.h>


namespace DogGE{
    namespace F1_2022{
        class CarStatusPackage{
            private:
            Header header;
CarStatusData carStatus[22];

            public:
            void setHeader(Header header);
void setCarStatus(CarStatusData* carStatus);

            Header getHeader();
CarStatusData* getCarStatus();

        };
    }
}

#endif                                