/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __FINAL_CLASSIFICATION_PACKAGE__
#define __FINAL_CLASSIFICATION_PACKAGE__
#pragma once

#include <stdint.h>
#include <DataClass/Header.h>
#include <DataClass/FinalClassificationData.h>


namespace DogGE{
    namespace F1_2022{
        class FinalClassificationPackage{
            private:
            Header header;
uint8_t numCars;
FinalClassificationData classification[22];

            public:
            void setHeader(Header header);
void setNumCars(uint8_t numCars);
void setClassification(FinalClassificationData* classification);

            Header getHeader();
uint8_t getNumCars();
FinalClassificationData* getClassification();

        };
    }
}

#endif                                