/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __HEADER__
#define __HEADER__
#pragma once

#include <stdint.h>


namespace DogGE{
    namespace F1_2022{
        class Header{
            private:
            uint16_t packetFormat;
uint8_t gameMajorVersion;
uint8_t gameMinorVersion;
uint8_t packetVersion;
uint8_t packetId;
uint64_t sessionUID;
float sessionTime;
uint32_t frameIdentifier;
uint8_t playerCarIndex;
uint8_t secondaryPlayerCarIndex;

            public:
            void setPacketFormat(uint16_t packetFormat);
void setGameMajorVersion(uint8_t gameMajorVersion);
void setGameMinorVersion(uint8_t gameMinorVersion);
void setPacketVersion(uint8_t packetVersion);
void setPacketId(uint8_t packetId);
void setSessionUID(uint64_t sessionUID);
void setSessionTime(float sessionTime);
void setFrameIdentifier(uint32_t frameIdentifier);
void setPlayerCarIndex(uint8_t playerCarIndex);
void setSecondaryPlayerCarIndex(uint8_t secondaryPlayerCarIndex);

            uint16_t getPacketFormat();
uint8_t getGameMajorVersion();
uint8_t getGameMinorVersion();
uint8_t getPacketVersion();
uint8_t getPacketId();
uint64_t getSessionUID();
float getSessionTime();
uint32_t getFrameIdentifier();
uint8_t getPlayerCarIndex();
uint8_t getSecondaryPlayerCarIndex();

        };
    }
}

#endif                                