/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __LAP_DATA_PACKAGE__
#define __LAP_DATA_PACKAGE__
#pragma once

#include <stdint.h>
#include <DataClass/Header.h>
#include <DataClass/LapData.h>


namespace DogGE{
    namespace F1_2022{
        class LapDataPackage{
            private:
            Header header;
LapData lapData[22];
uint8_t timeTrialPBCarIdx;
uint8_t timeTrialRivalCarIdx;

            public:
            void setHeader(Header header);
void setLapData(LapData* lapData);
void setTimeTrialPBCarIdx(uint8_t timeTrialPBCarIdx);
void setTimeTrialRivalCarIdx(uint8_t timeTrialRivalCarIdx);

            Header getHeader();
LapData* getLapData();
uint8_t getTimeTrialPBCarIdx();
uint8_t getTimeTrialRivalCarIdx();

        };
    }
}

#endif                                