/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __LOBBY_INFO_PACKAGE__
#define __LOBBY_INFO_PACKAGE__
#pragma once

#include <stdint.h>
#include <DataClass/Header.h>
#include <DataClass/LobbyInfoData.h>


namespace DogGE{
    namespace F1_2022{
        class LobbyInfoPackage{
            private:
            Header header;
uint8_t numPlayers;
LobbyInfoData lobbyInfo[22];

            public:
            void setHeader(Header header);
void setNumPlayers(uint8_t numPlayers);
void setLobbyInfo(LobbyInfoData* lobbyInfo);

            Header getHeader();
uint8_t getNumPlayers();
LobbyInfoData* getLobbyInfo();

        };
    }
}

#endif                                