/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef __TYRE_STINT_HISTORY_DATA__
#define __TYRE_STINT_HISTORY_DATA__
#pragma once

#include <stdint.h>


namespace DogGE{
    namespace F1_2022{
        class TyreStintHistoryData{
            private:
            uint8_t endLap;
uint8_t tyreActualCompound;
uint8_t tyreVisualCompound;

            public:
            void setEndLap(uint8_t endLap);
void setTyreActualCompound(uint8_t tyreActualCompound);
void setTyreVisualCompound(uint8_t tyreVisualCompound);

            uint8_t getEndLap();
uint8_t getTyreActualCompound();
uint8_t getTyreVisualCompound();

        };
    }
}

#endif                                