/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/CarDamagePackage.h>

namespace DogGE{
    namespace F1_2022{
        Header CarDamagePackage::getHeader(){return this->header;}
CarDamageData* CarDamagePackage::getCarDamage(){return this->carDamage;}

        void CarDamagePackage::setHeader(Header header){this->header = header;}
void CarDamagePackage::setCarDamage(CarDamageData* carDamage){for(int i=0;i<22;i++){
this->carDamage[i] = carDamage[i];
}
}

    }
}                    