/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/CarSetupData.h>

namespace DogGE{
    namespace F1_2022{
        uint8_t CarSetupData::getFrontWing(){return this->frontWing;}
uint8_t CarSetupData::getRearWing(){return this->rearWing;}
uint8_t CarSetupData::getOnThrottle(){return this->onThrottle;}
uint8_t CarSetupData::getOffThrottle(){return this->offThrottle;}
float CarSetupData::getFrontCamber(){return this->frontCamber;}
float CarSetupData::getRearCamber(){return this->rearCamber;}
float CarSetupData::getFrontToe(){return this->frontToe;}
float CarSetupData::getRearToe(){return this->rearToe;}
uint8_t CarSetupData::getFrontSuspension(){return this->frontSuspension;}
uint8_t CarSetupData::getRearSuspension(){return this->rearSuspension;}
uint8_t CarSetupData::getFrontAntiRollBar(){return this->frontAntiRollBar;}
uint8_t CarSetupData::getRearAntiRollBar(){return this->rearAntiRollBar;}
uint8_t CarSetupData::getFrontSuspensionHeight(){return this->frontSuspensionHeight;}
uint8_t CarSetupData::getRearSuspensionHeight(){return this->rearSuspensionHeight;}
uint8_t CarSetupData::getBreakePressure(){return this->breakePressure;}
uint8_t CarSetupData::getBreakeBias(){return this->breakeBias;}
float CarSetupData::getRearLeftTyrePressure(){return this->rearLeftTyrePressure;}
float CarSetupData::getRearRightTyrePressure(){return this->rearRightTyrePressure;}
float CarSetupData::getFrontLeftTyrePressure(){return this->frontLeftTyrePressure;}
float CarSetupData::getFrontRightTyrePressure(){return this->frontRightTyrePressure;}
uint8_t CarSetupData::getBallast(){return this->ballast;}
float CarSetupData::getFuelLoad(){return this->fuelLoad;}

        void CarSetupData::setFrontWing(uint8_t frontWing){this->frontWing = frontWing;}
void CarSetupData::setRearWing(uint8_t rearWing){this->rearWing = rearWing;}
void CarSetupData::setOnThrottle(uint8_t onThrottle){this->onThrottle = onThrottle;}
void CarSetupData::setOffThrottle(uint8_t offThrottle){this->offThrottle = offThrottle;}
void CarSetupData::setFrontCamber(float frontCamber){this->frontCamber = frontCamber;}
void CarSetupData::setRearCamber(float rearCamber){this->rearCamber = rearCamber;}
void CarSetupData::setFrontToe(float frontToe){this->frontToe = frontToe;}
void CarSetupData::setRearToe(float rearToe){this->rearToe = rearToe;}
void CarSetupData::setFrontSuspension(uint8_t frontSuspension){this->frontSuspension = frontSuspension;}
void CarSetupData::setRearSuspension(uint8_t rearSuspension){this->rearSuspension = rearSuspension;}
void CarSetupData::setFrontAntiRollBar(uint8_t frontAntiRollBar){this->frontAntiRollBar = frontAntiRollBar;}
void CarSetupData::setRearAntiRollBar(uint8_t rearAntiRollBar){this->rearAntiRollBar = rearAntiRollBar;}
void CarSetupData::setFrontSuspensionHeight(uint8_t frontSuspensionHeight){this->frontSuspensionHeight = frontSuspensionHeight;}
void CarSetupData::setRearSuspensionHeight(uint8_t rearSuspensionHeight){this->rearSuspensionHeight = rearSuspensionHeight;}
void CarSetupData::setBreakePressure(uint8_t breakePressure){this->breakePressure = breakePressure;}
void CarSetupData::setBreakeBias(uint8_t breakeBias){this->breakeBias = breakeBias;}
void CarSetupData::setRearLeftTyrePressure(float rearLeftTyrePressure){this->rearLeftTyrePressure = rearLeftTyrePressure;}
void CarSetupData::setRearRightTyrePressure(float rearRightTyrePressure){this->rearRightTyrePressure = rearRightTyrePressure;}
void CarSetupData::setFrontLeftTyrePressure(float frontLeftTyrePressure){this->frontLeftTyrePressure = frontLeftTyrePressure;}
void CarSetupData::setFrontRightTyrePressure(float frontRightTyrePressure){this->frontRightTyrePressure = frontRightTyrePressure;}
void CarSetupData::setBallast(uint8_t ballast){this->ballast = ballast;}
void CarSetupData::setFuelLoad(float fuelLoad){this->fuelLoad = fuelLoad;}

    }
}                    