/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/CarTelemetryPackage.h>

namespace DogGE{
    namespace F1_2022{
        Header CarTelemetryPackage::getHeader(){return this->header;}
CarTelemetryData* CarTelemetryPackage::getCarTelemetry(){return this->carTelemetry;}
uint8_t CarTelemetryPackage::getMfdPanelIndex(){return this->mfdPanelIndex;}
uint8_t CarTelemetryPackage::getMfdPanelIndexSecondaryPlayer(){return this->mfdPanelIndexSecondaryPlayer;}
int8_t CarTelemetryPackage::getSuggestedGear(){return this->suggestedGear;}

        void CarTelemetryPackage::setHeader(Header header){this->header = header;}
void CarTelemetryPackage::setCarTelemetry(CarTelemetryData* carTelemetry){for(int i=0;i<22;i++){
this->carTelemetry[i] = carTelemetry[i];
}
}
void CarTelemetryPackage::setMfdPanelIndex(uint8_t mfdPanelIndex){this->mfdPanelIndex = mfdPanelIndex;}
void CarTelemetryPackage::setMfdPanelIndexSecondaryPlayer(uint8_t mfdPanelIndexSecondaryPlayer){this->mfdPanelIndexSecondaryPlayer = mfdPanelIndexSecondaryPlayer;}
void CarTelemetryPackage::setSuggestedGear(int8_t suggestedGear){this->suggestedGear = suggestedGear;}

    }
}                    