/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/LapDataPackage.h>

namespace DogGE{
    namespace F1_2022{
        Header LapDataPackage::getHeader(){return this->header;}
LapData* LapDataPackage::getLapData(){return this->lapData;}
uint8_t LapDataPackage::getTimeTrialPBCarIdx(){return this->timeTrialPBCarIdx;}
uint8_t LapDataPackage::getTimeTrialRivalCarIdx(){return this->timeTrialRivalCarIdx;}

        void LapDataPackage::setHeader(Header header){this->header = header;}
void LapDataPackage::setLapData(LapData* lapData){for(int i=0;i<22;i++){
this->lapData[i] = lapData[i];
}
}
void LapDataPackage::setTimeTrialPBCarIdx(uint8_t timeTrialPBCarIdx){this->timeTrialPBCarIdx = timeTrialPBCarIdx;}
void LapDataPackage::setTimeTrialRivalCarIdx(uint8_t timeTrialRivalCarIdx){this->timeTrialRivalCarIdx = timeTrialRivalCarIdx;}

    }
}                    