/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/LapHistoryData.h>

namespace DogGE{
    namespace F1_2022{
        uint32_t LapHistoryData::getLapTimeInMS(){return this->lapTimeInMS;}
uint16_t LapHistoryData::getSector1TimeInMs(){return this->sector1TimeInMs;}
uint16_t LapHistoryData::getSector2TimeInMs(){return this->sector2TimeInMs;}
uint16_t LapHistoryData::getSector3TimeInMs(){return this->sector3TimeInMs;}
uint8_t LapHistoryData::getLapValidBitFlags(){return this->lapValidBitFlags;}

        void LapHistoryData::setLapTimeInMS(uint32_t lapTimeInMS){this->lapTimeInMS = lapTimeInMS;}
void LapHistoryData::setSector1TimeInMs(uint16_t sector1TimeInMs){this->sector1TimeInMs = sector1TimeInMs;}
void LapHistoryData::setSector2TimeInMs(uint16_t sector2TimeInMs){this->sector2TimeInMs = sector2TimeInMs;}
void LapHistoryData::setSector3TimeInMs(uint16_t sector3TimeInMs){this->sector3TimeInMs = sector3TimeInMs;}
void LapHistoryData::setLapValidBitFlags(uint8_t lapValidBitFlags){this->lapValidBitFlags = lapValidBitFlags;}

    }
}                    