/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/MarshalZone.h>

namespace DogGE{
    namespace F1_2022{
        float MarshalZone::getZoneStart(){return this->zoneStart;}
int8_t MarshalZone::getZoneFlag(){return this->zoneFlag;}

        void MarshalZone::setZoneStart(float zoneStart){this->zoneStart = zoneStart;}
void MarshalZone::setZoneFlag(int8_t zoneFlag){this->zoneFlag = zoneFlag;}

    }
}                    