/**
 * @file F1DataClassTemplate.cpp
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#include <DataClass/ParticipantsPackage.h>

namespace DogGE{
    namespace F1_2022{
        Header ParticipantsPackage::getHeader(){return this->header;}
uint8_t ParticipantsPackage::getNumActiveCars(){return this->numActiveCars;}
ParticipantsData* ParticipantsPackage::getParticipants(){return this->participants;}

        void ParticipantsPackage::setHeader(Header header){this->header = header;}
void ParticipantsPackage::setNumActiveCars(uint8_t numActiveCars){this->numActiveCars = numActiveCars;}
void ParticipantsPackage::setParticipants(ParticipantsData* participants){for(int i=0;i<22;i++){
this->participants[i] = participants[i];
}
}

    }
}                    