/**
 * @file F1DataClassTemplate.h
 * @author Philipp Holzmann (Philipp1990@web.de)
 * @brief 
 * @version 1.0
 * @date 2022-05-14
 * 
 * @copyright Copyright (c) 2022
 * 
 * This file ist generated by the f1GameParserGenerator Program. Any changes will be overriden.
 * 
 */

#ifndef ____CarMotionData_ENTITY____
#define ____CarMotionData_ENTITY____
#pragma once

#include <stdint.h>
#include <AbstractEntity.h>



namespace DogGE{
    namespace F1_2022{
        class CarMotionDataEntity: public DogGE::Database::AbstractEntity{
            private:
            float worldPositionX;
float worldPositionY;
float worldPositionZ;
float worldVelocityX;
float worldVelocityY;
float worldVelocityZ;
int16_t worldForwardDirX;
int16_t worldForwardDirY;
int16_t worldForwardDirZ;
int16_t worldRightDirX;
int16_t worldRightDirY;
int16_t worldRightDirZ;
float gForceLateral;
float gForceLongitudinal;
float gForceVertical;
float yaw;
float pitch;
float roll;

            public:
            CarMotionDataEntity();
CarMotionDataEntity(char* rawData,int size,int offset=0);


            void setWorldPositionX(float worldPositionX);
void setWorldPositionY(float worldPositionY);
void setWorldPositionZ(float worldPositionZ);
void setWorldVelocityX(float worldVelocityX);
void setWorldVelocityY(float worldVelocityY);
void setWorldVelocityZ(float worldVelocityZ);
void setWorldForwardDirX(int16_t worldForwardDirX);
void setWorldForwardDirY(int16_t worldForwardDirY);
void setWorldForwardDirZ(int16_t worldForwardDirZ);
void setWorldRightDirX(int16_t worldRightDirX);
void setWorldRightDirY(int16_t worldRightDirY);
void setWorldRightDirZ(int16_t worldRightDirZ);
void setGForceLateral(float gForceLateral);
void setGForceLongitudinal(float gForceLongitudinal);
void setGForceVertical(float gForceVertical);
void setYaw(float yaw);
void setPitch(float pitch);
void setRoll(float roll);

            float getWorldPositionX();
float getWorldPositionY();
float getWorldPositionZ();
float getWorldVelocityX();
float getWorldVelocityY();
float getWorldVelocityZ();
int16_t getWorldForwardDirX();
int16_t getWorldForwardDirY();
int16_t getWorldForwardDirZ();
int16_t getWorldRightDirX();
int16_t getWorldRightDirY();
int16_t getWorldRightDirZ();
float getGForceLateral();
float getGForceLongitudinal();
float getGForceVertical();
float getYaw();
float getPitch();
float getRoll();


            virtual std::string getTableName();
            virtual std::string getTableDefinition();
            
            virtual void matchIntData(std::string column,int data);
            virtual void matchInt64Data(std::string column,int64_t data);
            virtual void matchRealData(std::string column,float data);
            virtual void matchStringData(std::string column,std::string data);
            virtual void matchRawData(std::string column,char* data,int length);

            virtual std::map<std::string,int> getIntMap();
            virtual std::map<std::string,int64_t> getInt64Map();
            virtual std::map<std::string,float> getRealMap();
            virtual std::map<std::string,std::string> getStringMap();
            virtual std::map<std::string,std::pair<char*,int>> getRawMap();
        };
    }
}

#endif                                                   